serverAddr = "{{ .Envs.SERVER_ADDR }}"
serverPort = {{ .Envs.SERVER_PORT }}
auth.token = "{{ .Envs.AUTH_TOKEN }}"

[[proxies]]
name = "{{ .Envs.PROXY_NAME }}"
type = "xtcp"
# Only users with the same secretKey as the server can access this service
secretKey = "{{ .Envs.SECRET_KEY }}"
localIP = "{{ .Envs.LOCAL_IP }}"
localPort = {{ .Envs.LOCAL_PORT }}